# Generated by Django 4.2.23 on 2025-07-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreport',
            name='in_progress',
            field=models.TextField(blank=True),
        ),
    ]
